### ISSUE TITLE
Something similar

### ISSUE THREAD

**Issue by dwendooley** [harout/alphabet-stamps#1]
Completely new to openscad, wondering if you have a variant that'll just put one letter on a pedestal big enough to support it. Basically I want to 3d print the Albanian alphabet in primary colors and glue them around a picture frame for baby pics.  Thanks if you can help.

**Comment by harout** [comment]
Sorry to be replying so late. I don't come here that often. 
Take  a look at letter_preview.scad, I think it does what you need. The other scad file will generate a mold and letter_preview.scad will show you what the rubber you pull out of the mold will look like. You will probably than have to mirror that (https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/The_OpenSCAD_Language#mirror).
